### ISSUE TITLE
Making a pull request to update the readme

### ISSUE THREAD

**Issue by SteveStrong** [atularen/ngx-monaco-editor#100]
Hello,  I want to use this library and I am happy to make contributions.    Right now I am a bit confused about using this for angular 6 projects and above.    Should the read me be updated to say

 
For angular version 5 use v5.x.x
```
npm install ngx-monaco-editor@5.0.0 --save
 ```
 
For angular version 6 use v6.x.x  and above
```
npm install ngx-monaco-editor@6.0.0 --save
 ```

**Comment by atul-wizni** [comment]
Updated in new release. Thanks :)
