### ISSUE TITLE
get modifiedModel value

### ISSUE THREAD

**Issue by nitslucky** [atularen/ngx-monaco-editor#121]
My html file looks like this: 

`<ngx-monaco-diff-editor class="template-editor" [options]="options" [originalModel]="originalModel" [modifiedModel]="modifiedModel"></ngx-monaco-diff-editor>`

`<button mat-raised-button color="accent" (click)="getModifiedModelValue()">GO</button>`

How can I get the pasted value from the right side of the editor on click of 'Go' button?

**Comment by nikita-fuchs** [comment]
You should put a two-way binding in place and all the changes should be reflected in the variable's value, like ``` [(modifiedModel)]="modifiedModel"> ``` - havn't tested, but this is how I do it in my non-diff view.

**Comment by nitslucky** [comment]
Thanks for the reply but I have already tried it and it didn't work.

**Comment by nitslucky** [comment]
Solved my problem hopefully my solution will help others:
So my .html files looks like this:
`<ngx-monaco-diff-editor class="template-editor" [options]="options" [originalModel]="originalModel" [modifiedModel]="modifiedModel" (onInit)="onInitEditor($event)"></ngx-monaco-diff-editor>`

`<button mat-raised-button color="accent" (click)="getModifiedModelValue()">GO</button>`

and in my .ts file: 
`public onInitEditor(event) {
    this.editor = event;
  }`

`public getModifiedModelValue() { 
   console.log(this.editor.modifiedEditor.getValue());
)`
