### ISSUE TITLE
http://localhost:4200/assets/monaco/vs/loader.js net::ERR_ABORTED 404 (Not Found) for Angular 7 project

### ISSUE THREAD

**Issue by dharam1986** [atularen/ngx-monaco-editor#122]
Hi,

I installed Monaco editor followed by instruction mentioned in github. However after adding  { "glob": "**/*", "input": "../node_modules/ngx-monaco-editor/assets/monaco", "output": "./assets/monaco/" } into angular.json, Still I am getting below error:
GET http://localhost:4200/assets/monaco/vs/loader.js net::ERR_ABORTED 404 (Not Found)

**Comment by maytanthegeek** [comment]
Hey @dharam1986 I had the same problem yesterday. I changed the glob to this and it works now:
```
{
    "glob": "**/*",
    "input": "node_modules/ngx-monaco-editor/assets/monaco",
    "output": "/assets/monaco/"
}
```

**Comment by dharam1986** [comment]
Yes Tanmay, I also use the same thing and correct input path for node modules.
Guys, Please rectify the path to avoid such silly issues.

**Comment by myopenresources** [comment]
@maytanthegeek   I had the same problem yesterday. I changed the glob to this,But I will still have a warning.  对于我这种强迫症的人来说，可能会比较纠结！

**Comment by joharzmn** [comment]
> Hey @dharam1986 I had the same problem yesterday. I changed the glob to this and it works now:
> 
> ```
> {
>     "glob": "**/*",
>     "input": "node_modules/ngx-monaco-editor/assets/monaco",
>     "output": "/assets/monaco/"
> }
> ```

Where we need to put this code?

**Comment by dijus87** [comment]
> > Hey @dharam1986 I had the same problem yesterday. I changed the glob to this and it works now:
> > ```
> > {
> >     "glob": "**/*",
> >     "input": "node_modules/ngx-monaco-editor/assets/monaco",
> >     "output": "/assets/monaco/"
> > }
> > ```
> 
> Where we need to put this code?

https://www.npmjs.com/package/ngx-monaco-editor
here you can find the step-by-step
but even with this changed code I get the same error

**Comment by joharzmn** [comment]
> > > Hey @dharam1986 I had the same problem yesterday. I changed the glob to this and it works now:
> > > ```
> > > {
> > >     "glob": "**/*",
> > >     "input": "node_modules/ngx-monaco-editor/assets/monaco",
> > >     "output": "/assets/monaco/"
> > > }
> > > ```
> > 
> > 
> > Where we need to put this code?
> 
> https://www.npmjs.com/package/ngx-monaco-editor
> here you can find the step-by-step

Thank you, Got it working.

**Comment by fitness23** [comment]
The same problem is happening at the moment. Thing is there isn't even an "assets/monaco" folder inside "node_modules/ngx-monaco-editor"

**Comment by vidhyasagarj** [comment]
I am also facing the same issue. no such folder found "assets/monaco" in "node_modules/ngx-monaco-editor"

**Comment by IceBjerg** [comment]
Same issue. 
I use angular 10, and the editor version is the beta (10.0.0-beta.1). 
Waiting for the fix. 

There is no such thing as assets inside the node_modules/ngx-monaco-editor/ folder. 

I switched back to 9.0.0 version (editor), and everything is working fine.

**Comment by dharam1986** [comment]
> Same issue.
> I use angular 10, and the editor version is the beta (10.0.0-beta.1).
> Waiting for the fix.
> 
> There is no such thing as assets inside the node_modules/ngx-monaco-editor/ folder.
> 
> I switched back to 9.0.0 version (editor), and everything is working fine.

I am also using Angular 10 and the editor working fine with me, with the same config

**Comment by pe2mbs** [comment]
Make sure you have added the following, first is already mentioned above, but it needs 
to copy the min-maps from monaco editor

                          { "glob": "**/*", 
				"input": "node_modules/ngx-monaco-editor/assets/monaco", 
				"output": "./assets/monaco/" 
			  },
			  { "glob": "**/*", 
				"input": "node_modules/monaco-editor/min-maps", 
				"output": "./assets/min-maps/" 
			  }

**Comment by masi456** [comment]
Can anybody comment if it is okay for `assets/monaco` to be missing from `node_modules/ngx-monaco-editor`? Can we fix this by reinstalling or something?

**Comment by PaulFenton** [comment]
I am also trying to use the latest version (10.0.0) with Angular 11 and getting the same issue, with the above changes to the "glob" config not fixing the issue.

As others have suggested, going back to 9.0.0 seems to be working for me.

**Comment by MikaStark** [comment]
There is no assets folder inside 10.0.0 but there is in 9.0.0

**Comment by shadcome** [comment]
Yes , with this help 
https://www.npmjs.com/package/ngx-monaco-editor
just use version 9.0.0

**Comment by dolanmiu** [comment]
Could you make v9.0.0 the default one when you do `npm install ngx-monaco-editor`?

I think you can set the `next` version to be `10.0.0-beta` (`npm install ngx-monaco-editor@next`) and `latest` to be `9`. Will help new users like me to get up and running a bit faster

**Comment by TaylorShane** [comment]
This issue was fixed for my by correct the glob paths AND defining a NgxMonacoEditorConfig block in app.module.ts as documented by the configurations section of the setup.

`const monacoConfig: NgxMonacoEditorConfig = {
  baseUrl: 'assets', // configure base path for monaco editor
  defaultOptions: { scrollBeyondLastLine: false }, // pass default options to be used
  onMonacoLoad: () => { console.log((<any>window).monaco); } // here monaco object will be available as window.monaco use this function to extend monaco editor functionalities.
};`

**Comment by timinsi** [comment]
> Make sure you have added the following, first is already mentioned above, but it needs
> to copy the min-maps from monaco editor
> 
> ```
>                       { "glob": "**/*", 
> 			"input": "node_modules/ngx-monaco-editor/assets/monaco", 
> 			"output": "./assets/monaco/" 
> 		  },
> 		  { "glob": "**/*", 
> 			"input": "node_modules/monaco-editor/min-maps", 
> 			"output": "./assets/min-maps/" 
> 		  }
> ```

You are awesome my friend!!!!! I got fix the problem with min-maps! Appreciate it!

**Comment by mohhsen67** [comment]
> Hey @dharam1986 I had the same problem yesterday. I changed the glob to this and it works now:
> 
> ```
> {
>     "glob": "**/*",
>     "input": "node_modules/ngx-monaco-editor/assets/monaco",
>     "output": "/assets/monaco/"
> }
> ```

This code solved my problem, too. Thank you.

**Comment by esteban-gs** [comment]
> Hey @dharam1986 I had the same problem yesterday. I changed the glob to this and it works now:
> 
> ```
> {
>     "glob": "**/*",
>     "input": "node_modules/ngx-monaco-editor/assets/monaco",
>     "output": "/assets/monaco/"
> }
> ```

Worked for me. Thanks!

**Comment by directcuteo** [comment]
This is what worked for me with Angular 12.

```
              {
                "glob": "**/*",
                "input": "node_modules/monaco-editor",
                "output": "./assets/monaco-editor/"
              },
              {
                "glob": "**/*",
                "input": "node_modules/monaco-editor/min-maps",
                "output": "./assets/min-maps/"
              }
```

**Comment by garycncf** [comment]
> This is what worked for me with Angular 12.
> 
> ```
>               {
>                 "glob": "**/*",
>                 "input": "node_modules/monaco-editor",
>                 "output": "./assets/monaco-editor/"
>               },
>               {
>                 "glob": "**/*",
>                 "input": "node_modules/monaco-editor/min-maps",
>                 "output": "./assets/min-maps/"
>               }
> ```

thanks,  worked for me with Angular 12.

**Comment by SammyDodgerr** [comment]
@directcuteo @garycncf  could you please post your angular.json and package.json files. I am struggling to get this going in angular 12 in a local stack.

**Comment by visualbuffer** [comment]
Thanks, worked with Angular 14
Angular.json :
  ```
  {
                "glob": "**/*",
                "input": "node_modules/monaco-editor",
                "output": "./assets/monaco-editor/"
              },
                {
                  "glob": "**/*",
                  "input": "node_modules/monaco-editor/min-maps",
                  "output": "./assets/min-maps/"
                },
```

Module : 
```

const monacoConfig: NgxMonacoEditorConfig = {
  defaultOptions: { scrollBeyondLastLine: false },
  baseUrl: './assets',
  onMonacoLoad: () => {
    const monaco = (window as any).monaco;
    console.log(monaco);
}
};

@NgModule({

  imports: [
    ...
    MonacoEditorModule.forRoot(),
  ],
  providers: [
    { provide: NGX_MONACO_EDITOR_CONFIG, useValue: monacoConfig }
  ]
})
```
