### ISSUE TITLE
angular 8 Ivy 

### ISSUE THREAD

**Issue by cesarcastmore** [atularen/ngx-monaco-editor#137]
I am migrating my application to Ivy  and developing dynamic modules, but when I  install monaco-editor and I start my server. I have the Error

    ERROR in src/app/app.component.html(1,20): Property 'options' does not exist on type 'HTMLElement'.

package.json

`{
  "name": "shiny-ivy-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.11",
    "@angular/common": "~8.2.11",
    "@angular/compiler": "~8.2.11",
    "@angular/core": "~8.2.11",
    "@angular/forms": "~8.2.11",
    "@angular/platform-browser": "~8.2.11",
    "@angular/platform-browser-dynamic": "~8.2.11",
    "@angular/router": "~8.2.11",
    "ngx-monaco-editor": "^8.1.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.12",
    "@angular/cli": "~8.3.12",
    "@angular/compiler-cli": "~8.2.11",
    "@angular/language-service": "~8.2.11",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}
`

**Comment by PetrosA** [comment]
I have also the same problem. Would be great if it would be compatible to Ivy

**Comment by cesarcastmore** [comment]
I have updated my application to ivy and I have been using ngx-monaco-editor in some developers of production. I am seeing that a developer commit the solution to be compatible to ivy. When will this commit push on master ?
