### ISSUE TITLE
Diff Editor Right Side Is Editable Although Readonly Is Set to True

### ISSUE THREAD

**Issue by Halfist** [atularen/ngx-monaco-editor#158]
I'm using side by side Diff Editor with `readonly: true` option. However, the right side is still editable. Am I missing something or this is a bug? Please note that with `readonly: false` option both sides are editable, so, the option actually works, but not completely.

**Comment by atul-wizni** [comment]
You can disable right side of editor in init method as mentioned in [comment](https://github.com/microsoft/monaco-editor/issues/27#issuecomment-228483763) 
```
onInit(diffEditor) {
    diffEditor.getModifiedEditor().updateOptions({readOnly:true});
}
```

**Comment by Halfist** [comment]
I don't have a reference of `diffEditor` in `onInit()`. If I try to pass `$event` from component template like `(onInit)="onInit($event)`, IDE shows an error "Invalid number of arguments, expected 0". I'm using Diff Editor like this: `<ngx-monaco-diff-editor [options]="editorOptions" [originalModel]="original" [modifiedModel]="modified" (onInit)="onInit()"></ngx-monaco-diff-editor>`. If instead of calling `diffEditor` I try to use `(window as any).monaco.editor`, which results in `(window as any).monaco.editor.getModifiedEditor().updateOptions({ readOnly: true });`, then I have an error "window.monaco.editor.getModifiedEditor is not a function".

**Comment by Halfist** [comment]
Thanks a lot, it works! I didn't know I can pass the editor reference from template to `onInit()` as `$event`.
