### ISSUE TITLE
Configure Script Location

### ISSUE THREAD

**Issue by janstadt** [atularen/ngx-monaco-editor#16]
Love the component, but i think it needs to allow for a configurable location for where the loader lives. We have a virtual app running on one of our servers and since there is a `/` in front of assets, the baseUrl is ignored. When we try to load up our app we get a 404 as the url goes from:
`https://app.com/virtualappname/assets/monaco/vs/loader.js` to `https://app.com/assets/monaco/vs/loader.js`. This prop could default to this and live off of the options object. 
https://github.com/atularen/ngx-monaco-editor/blob/master/src/platform/editor/editor.component.ts#L102

For now i plan on just extending the editor and overriding the oninit method.

**Comment by Xcorpio** [comment]
Good, I need this feature too.

**Comment by atul-wizni** [comment]
@janstadt @Xcorpio v2.0.0 supports config for baseUrl. for more details refer [README -> Configurations](https://github.com/atularen/ngx-monaco-editor#configurations)
