### ISSUE TITLE
YAML Support

### ISSUE THREAD

**Issue by viccsjain** [atularen/ngx-monaco-editor#18]
Hi @atul-wizni ,

Thanks for this component. it is really helping me in my project.
I would like to know how we can support YAML file in this editor ?
If yes, will it show syntax errors as well ?
What configuration we will be required to change.

Appreciate your help on this.

**Comment by atul-wizni** [comment]
This is just an wrapper for Monaco Editor. All functionalities that are supported can be found [here](https://github.com/Microsoft/monaco-editor).

To get list of available languages use can use `monaco.languages.getLanguages()` and pass value in language option to ngx-monaco-editor component.
