### ISSUE TITLE
DOES NOT SUPPORT angular 4 or 2. 

### ISSUE THREAD

**Issue by moorthi07** [atularen/ngx-monaco-editor#22]
I tried from angular 4.  

Error: Metadata version mismatch for module  /node_modules/ngx-monaco-editor/index.d.ts, found version 4, expected 3, resolving symbol AppModule in app/app.module.ts

you are using angular 5 , pl. change the description to support only 5 .

**Comment by atul-wizni** [comment]
Published v3.x.x for angular 4

**Comment by moorthi07** [comment]
v3.x not showing the editor.
Also it needs,
ngDefaultControl  and a 'name' attribute like this,
  `<ngx-monaco-editor [options]="editorOptions" [(ngModel)]="content" **name**="content" style="display:block; height: 80vh; width:100%" **ngDefaultControl** ></ngx-monaco-editor>`

**Comment by atul-wizni** [comment]
Please refer #27
