### ISSUE TITLE
Not working with Angular 12

### ISSUE THREAD

**Issue by pavangayakwad** [atularen/ngx-monaco-editor#229]
**_Steps to reproduce_** : is following step by step as explained here (https://github.com/atularen/ngx-monaco-editor) using Angular CLI 12+

The html tag <ngx-monaco-editor> does not resolve or recognized and the output is empty screen. 

![image](https://user-images.githubusercontent.com/1834890/132370926-f6be19ea-885d-41dc-8234-95d0e139f08f.png)

**Comment by klammal** [comment]
Actually it does work, you just need ti import the the monacoModule again in the same module where you want to use it

**Comment by pavangayakwad** [comment]
Yes, that solved my problem. Thanks. 👍

**Comment by valentinoPereira** [comment]
Can you close this issue @pavangayakwad ?
