### ISSUE TITLE
Doubts about monaco.editor.create

### ISSUE THREAD

**Issue by matheusnicolas** [atularen/ngx-monaco-editor#231]
Hey guys, I'm trying to use _monaco.editor.create_ and I'm facing this error:

Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')

how could I do this if I'm using ngx-monaco-editor and I want to configure my _monaco-config.ts_:

`
let editor = monaco.editor.create(document.getElementById('container'), {
        theme: 'my-theme',
        language: "my-language"
 });
`

My html angular code:

`<div class="monaco-div">
    <ngx-monaco-editor class="editor custom--monaco-editor" *ngIf="!loading" [options]="editorOptions" [(ngModel)]="data.code">
    </ngx-monaco-editor>
    <div class="transparent-layer"></div>
  </div>`

I tried to use window.onload, addEventListener but nothing works, I don't know how could I try to solve this problem. I suspect it's something because I already have the ngx component in the html, but I might be wrong.

**Comment by matheusnicolas** [comment]
I got it working, no worries!

**Comment by mike-luabase** [comment]
@matheusnicolas what'd you change?
