### ISSUE TITLE
Doc. correction. To use 'ngModel' you need FormsModule imported

### ISSUE THREAD

**Issue by moorthi07** [atularen/ngx-monaco-editor#24]
Pl. add this code to reademe file , could save some time for first time users. Tx.

`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {FormsModule} from '@angular/forms';
import { MonacoEditorModule } from 'ngx-monaco-editor';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule, FormsModule, MonacoEditorModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

**Comment by atul-wizni** [comment]
Docs updated
