### ISSUE TITLE
Material Design components for Angular

### ISSUE THREAD

**Issue by carlas0fia** [atularen/ngx-monaco-editor#253]
Hello,
This is not really an issue but a question, are the Material Design components for Angular supported?
We have a page builder on top of the Monaco editor (html), and after we introduced the new material components it was all messed up.
Is this possible to achieve? I couldn't find anything related on the configuration yet.

Thank you for any help you can offer,
Carla Lima

**Comment by alessiostalla** [comment]
I use ngx-monaco-editor with Angular Material with no problems. Maybe some custom CSS of yours is conflicting with Material?

**Comment by carlas0fia** [comment]
Hello!
We realized by now, that it's because we are rendering the html that was made in the editor, from the database into a div. 
It was used before as sort of a page designer, and with only native html and custom classes worked fine, but as soon as we added material design elements it needs to be rendered properly.
I know now the editor has nothing to do with the issue so this can be closed.
But still, thank you for your help!
