### ISSUE TITLE
support angular 16 

### ISSUE THREAD

**Issue by niltor** [atularen/ngx-monaco-editor#264]
Someone can support angular 16?

@miki995

**Comment by miki995** [comment]
Yes, but in new repo probably next weekSent from my iPhoneOn May 6, 2023, at 10:41 AM, Ater_NilTor ***@***.***> wrote:﻿
Someone can support angular 16?
@miki995

**Comment by niltor** [comment]
I had tried 
```json
"ngx-monaco-editor-v2": "^15.0.1"
```
with Angular 16, it works well!
