### ISSUE TITLE
Got error in Angular4

### ISSUE THREAD

**Issue by z0nka1** [atularen/ngx-monaco-editor#27]
When I try to use ngx-monaco-editor in my Angular app,I got the follow error:
```
ERROR in Error: Metadata version mismatch for module C:/Users/kai/Desktop/0110/node_modules/ngx-mona
co-editor/index.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/kai/Deskto
p/0110/src/app/app.module.ts
```
Angular verson: 4.1.3
Angular-cli verson: 1.4.3
ngx-monaco-editor verson: 3.0.0

Anyone help me?
I just did it follow the README

**Comment by davidcblaney** [comment]
Hi,

I am having the same issue with ngx-monaco-editor verson 3.0.2.

I'm wondering if the package.json was changed and was published without deleting and reinstalling the node_modules and therefore built with a different version of Angular than expected?

**Comment by atul-wizni** [comment]
I have tried v3.0.2 with cli@1.4.7
its working fine will you please verify
[ng1.4.7.zip](https://github.com/atularen/ngx-monaco-editor/files/1688172/ng1.4.7.zip)

**Comment by z0nka1** [comment]
When I update cli@1.4.3 to 1.4.7,it work now!
You can try it. @davidcblaney

**Comment by davidcblaney** [comment]
Upgrading both editor and the CLI worked.

For ref I was using CLI v1.2.1

Many thanks.

**Comment by rafamds** [comment]
Hey, is this solved? Thanks
