### ISSUE TITLE
NgZone not defined

### ISSUE THREAD

**Issue by crufter** [atularen/ngx-monaco-editor#31]
Hi there!

This is what I get when I load the page with monaco editor on it:

```base-editor.js:102 Uncaught ReferenceError: NgZone is not defined```

Is this something you have seen?

**Comment by nischi** [comment]
I have the same error

**Comment by crufter** [comment]
I have to say even after hours and hours of google I and trying to fix this I could not find a solution.

**Comment by atul-wizni** [comment]
What are the angular, angular-cli, ngx-monaco-editor versions you are using?

**Comment by nischi** [comment]
That works like a charm. Thanks a lot @atul-wizni

**Comment by crufter** [comment]
Seems to not throw the error. The editor does not appear so far but that will be a mistake on my end I think.
