### ISSUE TITLE
jQuery language add on? (request)

### ISSUE THREAD

**Issue by SGissubel** [atularen/ngx-monaco-editor#32]
First of all, I searched high and low for an editor like this one, (the ngx-monaco-editor version... not the covalent version -- there are ZERO resources for using it, and it is insanely difficult)  This version was so simple to set up... it's incredible. 

However, resources are still a little limited for this version as well, including: what languages are available, how to implement all the different things I have seen in the demos, etc. 

But down to brass tax here, from the languages that I found, jQuery is not one of the ones included, and I was hoping that could be an add on to the languages that are currently available (also, a list would help greatly). Thanks!

**Comment by atul-wizni** [comment]
Thanks @SGissubel. 
This is just the wrapper over monaco editor so all options that are provided should work here. for complete list of features and docs/demo you can refer below links:

https://microsoft.github.io/monaco-editor/playground.html
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html

For JQuery language 'javascript' will serve the purpose or you can work on custom language requirements refer custom language demo in playground.
