### ISSUE TITLE
How to register own language ?

### ISSUE THREAD

**Issue by DevidCIC** [atularen/ngx-monaco-editor#36]
I want to create a own language syntax highlighting as described here: [https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages](url).

How can I do that with ngx-monaco-editor, is there a example ?

**Comment by DevidCIC** [comment]
Ok now I get it, I have to use the example with the Configuration. But it is not that convenient that this has to be defined in the module. 

`
const monacoConfig: NgxMonacoEditorConfig = {
  onMonacoLoad: () => {
        (<any>window).monaco.languages.register({ id: 'mySpecialLanguage' });

        // Register a tokens provider for the language
        (<any>window).monaco.languages.setMonarchTokensProvider('mySpecialLanguage', {
            tokenizer: {
                root: [
                    [/\[error.*/, 'custom-error'],
                    [/\[notice.*/, 'custom-notice'],
                    [/\[info.*/, 'custom-info'],
                    [/\[[a-zA-Z 0-9:]+\]/, 'custom-date'],
                ]
            }
        });

        (<any>window).monaco.editor.defineTheme('myCoolTheme', {
            base: 'vs',
            inherit: false,
            rules: [
                { token: 'custom-info', foreground: '808080' },
                { token: 'custom-error', foreground: 'ff0000', fontStyle: 'bold' },
                { token: 'custom-notice', foreground: 'FFA500' },
                { token: 'custom-date', foreground: '008800' },
            ]
        });

        (<any>window).monaco.languages.registerCompletionItemProvider('mySpecialLanguage', {
            provideCompletionItems: () => {
                return [
                    {
                        label: 'simpleText',
                        kind: (<any>window).monaco.languages.CompletionItemKind.Text
                    }, {
                        label: 'testing',
                        kind: (<any>window).monaco.languages.CompletionItemKind.Keyword,
                        insertText: {
                            value: 'testing(${1:condition})'
                        }
                    },
                    {
                        label: 'ifelse',
                        kind: (<any>window).monaco.languages.CompletionItemKind.Snippet,
                        insertText: {
                            value: [
                                'if (${1:condition}) {',
                                '\t$0',
                                '} else {',
                                '\t',
                                '}'
                            ].join('\n')
                        },
                        documentation: 'If-Else Statement'
                    }
                ];
            }
        });

        console.log((<any>window).monaco);

    }
};
`

Writing something like [error] will be now shown in red.

**Comment by atul-wizni** [comment]
As its an wrapper over monaco-editor. i have tried to keep minimum possible code inside the module. Custom language syntax highlighting should be owned by users so these can't be provided by module.

**Comment by Myrmex** [comment]
Thanks, this was very useful, but I had to change something for Angular 7. For reference, I paste here my up-to-date code in a dummy Angular 7 app, plus [this link](https://github.com/Microsoft/monaco-editor/blob/master/test/playground.generated/extending-language-services-custom-languages.html) for a custom language sample.

```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

import { MonacoEditorModule, NgxMonacoEditorConfig } from 'ngx-monaco-editor';
import { ReactiveFormsModule } from '@angular/forms';

export function myMonacoLoad() {
  (window as any).monaco.languages.register({ id: 'dummy' });

  // Register a tokens provider for the language
  (window as any).monaco.languages.setMonarchTokensProvider('dummy', {
    tokenizer: {
      root: [
        [/\[error.*/, 'custom-error'],
        [/\[notice.*/, 'custom-notice'],
        [/\[info.*/, 'custom-info'],
        [/\[[a-zA-Z 0-9:]+\]/, 'custom-date'],
      ]
    }
  });

  (window as any).monaco.editor.defineTheme('dummy-light', {
    base: 'vs',
    inherit: false,
    rules: [
      { token: 'custom-info', foreground: '808080' },
      { token: 'custom-error', foreground: 'ff0000', fontStyle: 'bold' },
      { token: 'custom-notice', foreground: 'FFA500' },
      { token: 'custom-date', foreground: '008800' },
    ]
  });

  (window as any).monaco.languages.registerCompletionItemProvider('dummy', {
    provideCompletionItems: () => {
      return [
        {
          label: 'simpleText',
          kind: (window as any).monaco.languages.CompletionItemKind.Text
        }, {
          label: 'testing',
          kind: (window as any).monaco.languages.CompletionItemKind.Keyword,
          insertText: {
            value: 'testing(${1:condition})'
          }
        },
        {
          label: 'ifelse',
          kind: (window as any).monaco.languages.CompletionItemKind.Snippet,
          insertText: {
            value: [
              'if (${1:condition}) {',
              '\t$0',
              '} else {',
              '\t',
              '}'
            ].join('\n')
          },
          documentation: 'If-Else Statement'
        }
      ];
    }
  });
}

const monacoConfig: NgxMonacoEditorConfig = {
  onMonacoLoad: myMonacoLoad
};

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    ReactiveFormsModule,
    MonacoEditorModule.forRoot(monacoConfig)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by baggiaraj** [comment]
> Thanks, this was very useful, but I had to change something for Angular 7. For reference, I paste here my up-to-date code in a dummy Angular 7 app, plus [this link](https://github.com/Microsoft/monaco-editor/blob/master/test/playground.generated/extending-language-services-custom-languages.html) for a custom language sample.
> 
> ```ts
> import { BrowserModule } from '@angular/platform-browser';
> import { NgModule } from '@angular/core';
> 
> import { AppComponent } from './app.component';
> 
> import { MonacoEditorModule, NgxMonacoEditorConfig } from 'ngx-monaco-editor';
> import { ReactiveFormsModule } from '@angular/forms';
> 
> export function myMonacoLoad() {
>   (window as any).monaco.languages.register({ id: 'dummy' });
> 
>   // Register a tokens provider for the language
>   (window as any).monaco.languages.setMonarchTokensProvider('dummy', {
>     tokenizer: {
>       root: [
>         [/\[error.*/, 'custom-error'],
>         [/\[notice.*/, 'custom-notice'],
>         [/\[info.*/, 'custom-info'],
>         [/\[[a-zA-Z 0-9:]+\]/, 'custom-date'],
>       ]
>     }
>   });
> 
>   (window as any).monaco.editor.defineTheme('dummy-light', {
>     base: 'vs',
>     inherit: false,
>     rules: [
>       { token: 'custom-info', foreground: '808080' },
>       { token: 'custom-error', foreground: 'ff0000', fontStyle: 'bold' },
>       { token: 'custom-notice', foreground: 'FFA500' },
>       { token: 'custom-date', foreground: '008800' },
>     ]
>   });
> 
>   (window as any).monaco.languages.registerCompletionItemProvider('dummy', {
>     provideCompletionItems: () => {
>       return [
>         {
>           label: 'simpleText',
>           kind: (window as any).monaco.languages.CompletionItemKind.Text
>         }, {
>           label: 'testing',
>           kind: (window as any).monaco.languages.CompletionItemKind.Keyword,
>           insertText: {
>             value: 'testing(${1:condition})'
>           }
>         },
>         {
>           label: 'ifelse',
>           kind: (window as any).monaco.languages.CompletionItemKind.Snippet,
>           insertText: {
>             value: [
>               'if (${1:condition}) {',
>               '\t$0',
>               '} else {',
>               '\t',
>               '}'
>             ].join('\n')
>           },
>           documentation: 'If-Else Statement'
>         }
>       ];
>     }
>   });
> }
> 
> const monacoConfig: NgxMonacoEditorConfig = {
>   onMonacoLoad: myMonacoLoad
> };
> 
> @NgModule({
>   declarations: [
>     AppComponent
>   ],
>   imports: [
>     BrowserModule,
>     ReactiveFormsModule,
>     MonacoEditorModule.forRoot(monacoConfig)
>   ],
>   providers: [],
>   bootstrap: [AppComponent]
> })
> export class AppModule { }
> ```

can you please provide any working editor like stackblitz or fiddle. i have tried but for me it's not working
