### ISSUE TITLE
Support to pass default json schema as parameter.

### ISSUE THREAD

**Issue by viccsjain** [atularen/ngx-monaco-editor#38]
In monaco editor, when we create model, it have option to pass default json schema. 

`var model = monaco.editor.createModel(jsonCode, 'json', 'internal://server/schema.json');
`
this schema will be default schema for monaco editor, it will validate our code against this schema.

Example:
1. Use following code at [playground](https://microsoft.github.io/monaco-editor/playground.html).
2. Click on Run button.
3. In editor, press `CTRL+ SPACE`.
4. This will auto suggest keys based on our schema.
```
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    schemas: [{
      fileMatch: ['foo.json'],
      schema: {
            type: "object",
            properties: {
                p1: {
                    enum: [ "v1", "v2"]
                }
            }
        }
    }]
});


var jsonCode = [
    '{',
    "}"
].join('\n');

var model = monaco.editor.createModel(jsonCode, 'json', 'internal://server/foo.json');

monaco.editor.create(document.getElementById("container"), {
    model: model
});

```

Expectation:
 ```
    <ngx-monaco-editor #editor class="size-width-100 size-height-96" 
          [options]="editorOptions" [(ngModel)]="content" (ngModelChange)="validateContent()"
          (onInit)="editorInit($event)">
        </ngx-monaco-editor>
```
Here it should take an optional parameter to pass json schema.

**Comment by viccsjain** [comment]
Thanks @atul-wizni

**Comment by atul-wizni** [comment]
Please check new version 4.1.0 to [Configure JSON Defaults](https://github.com/atularen/ngx-monaco-editor/blob/master/README.md#configure-json-defaults)

**Comment by viccsjain** [comment]
Thanks @atul-wizni for quick response.

**Comment by viccsjain** [comment]
This worked for me. 
Please close the issue.
