### ISSUE TITLE
Monaco monaco.d.ts Typings

### ISSUE THREAD

**Issue by Devid-** [atularen/ngx-monaco-editor#39]
I see that under ngx-monaco-editor/src/platform/editor/   there is monaco.d.ts file. Can you export this or something so that I could use it in my TypeScript ?

**Comment by atul-wizni** [comment]
This file is already exported as 'node_modules/ngx-monaco-editor/monaco.d.ts'

**Comment by BlindDespair** [comment]
@atul-wizni as I noticed, file is there, but there is no export keyword and it's not exported in index.ts either. So even though it's there it cannot be imported.

**Comment by atul-wizni** [comment]
with version 4.1.0 use can use monaco instance directly as it has be added in types.d.ts as reference path.

**Comment by DevidCIC** [comment]
@atul-wizni How can I get the monaco editor instance ?  I would like to know if I the editor has Focus.
On Escape if the editor has Focus I would like to blur.  

```typescript    
@HostListener('keydown', ['$event']) public onKeyUp(evt: KeyboardEvent) {
        if (evt.keyCode === KeyCode.esc) {
            // check if the editor has focus
            monaco.editor ..... ???
        }
    }
```

**Comment by DevidCIC** [comment]
Now I am using the onInit and there I am doing this, but not sure if there is not a better way :

```typescript
  public clarionEditor;
 public onEditorInit(editor) {
        this.clarionEditor = editor;
    }
```
