### ISSUE TITLE
Code does not get shown unless component is redrawn.

### ISSUE THREAD

**Issue by headdetect** [atularen/ngx-monaco-editor#40]
Only happens with the latest version (4.1.0). When I downgrade to 4.0.1 it's all hunky dorey.

Here's a sample repo: https://github.com/headdetect/monaco-bug

Here's a gif of the bug: ![Imgur](https://i.imgur.com/vvfHnRD.gif)

**Comment by atul-wizni** [comment]
Fixed in v4.1.1

**Comment by rluvaton** [comment]
Same issue here
