### ISSUE TITLE
ModelService: Cannot add model because it already exists

### ISSUE THREAD

**Issue by CoderPoet** [atularen/ngx-monaco-editor#48]
```
ERROR Error: Uncaught (in promise): Error: ModelService: Cannot add model because it already exists!
```

**Comment by viccsjain** [comment]
@CoderPoet this error mostly comes when we dispose the editor without disposing model.
Could you please provide more details ?
Are you disposing editor and then trying to create again ?

**Comment by CoderPoet** [comment]
Thank you for your reply. I created the editor twice then error .
![image](https://user-images.githubusercontent.com/19374680/40409792-814e33c0-5e9e-11e8-9435-4ee0a9bcf1a1.png)

**Comment by CoderPoet** [comment]
@viccsjain 
![image](https://user-images.githubusercontent.com/19374680/40409835-a2b3c0f2-5e9e-11e8-9fec-fea56bd89f6f.png)

**Comment by amarnath-mishra** [comment]
Did you find any solution for this ??

**Comment by viccsjain** [comment]
It will be easy to diagnose if you can provide https://stackblitz.com/ page for this issue.

**Comment by xocoatzin** [comment]
I found the same error.

I create an editor in one of my components, when navigate away and come back, I see this in the console. 

```
export class SomeComponent implements OnInit { 
  editorOptions = {
    theme: 'vs',
    // theme: 'vs-dark',
    language: 'json',
  }; 

  model: NgxEditorModel = {
    value: '{}',
    language: 'json',
    uri: 'foo.json'
  };
```

And in my template:

```
<ngx-monaco-editor [options]="editorOptions" [model]="model"></ngx-monaco-editor>
```

As mentioned by @viccsjain, I'm not currently disposing of the model. Unfortunately I was not able to find the right way to do it in the documentation. What would it be the correct way of doing it?

**Comment by JoshYaxley** [comment]
Did you find a fix for this @xocoatzin ?

I'm experiencing the same error on navigation.

**Comment by JoshYaxley** [comment]
@xocoatzin For our situtation (not multiple editors, but routing back and forth to an editor), I've done a couple of "hacks" to get around it.

The main one is to simply force a browser refresh if it fails to load. Not very elegant because then the user has to download your whole app again:

``` typescript
ngOnInit(): void {
  setTimeout(() => {
    const editorContainers = document.getElementsByClassName('editor-container');
    const editorFailedToLoad =
      editorContainers.length > 0 && editorContainers[0].innerHTML === '';

    if (editorFailedToLoad) location.reload();
  }, 1000);
}
```

The second fix reduces the amount of times this is necessary by using "sticky routing" (when a user leaves a route, the components aren't destroyed and are re-used when they return - this means the editor doesn't get recreated):

A new class, `CustomRouteReuseStrategy`:
``` typescript
import {
  RouteReuseStrategy,
  DetachedRouteHandle,
  ActivatedRouteSnapshot
} from '@angular/router';

export class CustomRouteReuseStrategy implements RouteReuseStrategy {
  handlers: { [key: string]: DetachedRouteHandle } = {};

  shouldDetach(route: ActivatedRouteSnapshot): boolean {
    return true;
  }

  store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle): void {
    this.handlers[route.routeConfig.path] = handle;
  }

  shouldAttach(route: ActivatedRouteSnapshot): boolean {
    return !!route.routeConfig && !!this.handlers[route.routeConfig.path];
  }

  retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle {
    if (!route.routeConfig) return null;
    return this.handlers[route.routeConfig.path];
  }

  shouldReuseRoute(
    future: ActivatedRouteSnapshot,
    current: ActivatedRouteSnapshot
  ): boolean {
    return future.routeConfig === current.routeConfig;
  }
}
```

> You can obviously adjust this class to fit your needs. This example uses sticky routing for every route.

And then in your `app.module.ts`:
``` typescript
...
providers: [
  { provide: RouteReuseStrategy, useClass: CustomRouteReuseStrategy }
]
...
```

This seems to fix the majority of navigation failures, and, when it doesn't, the first "hack" kicks in to refresh the page.

Not ideal at all, but manageable.

**Comment by xocoatzin** [comment]
@JoshYaxley Not a solution but a work-around:

Somewhere in the initialization function:

```
        monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
          validate: true,
          schemas: [
            {
              fileMatch: ['*'],
              uri: 'https://foo.bar.com/foobar.json',
              schema: schema
            }
          ]
        });

        const model = monaco.editor.getModels()[0];
        monaco.editor.setModelLanguage(model, 'json');
        model.setValue(this.workflow.payload);
```

**Comment by ajaybabum** [comment]
write different URI names then it will fix [
![cannot add modal](https://user-images.githubusercontent.com/22117265/43761559-1086ea2a-9a43-11e8-9cfd-9ccfd3573b94.png)
](url)

**Comment by skylarmb** [comment]
@ajaybabum this was my problem as well. I was initializing multiple instances and the `uri`s were not unique. Thanks.

**Comment by benbenqiang** [comment]
@ajaybabum Thanks

**Comment by IamFonky** [comment]
What do you mean by URI names must be unique?

I made a very simple example and i can't make it work without this error (the error also happened when i used monaco-editor directly).

[Look here](https://codesandbox.io/s/monaco-editor-getmodeid-343ck)

**Comment by steve-heine** [comment]
@ajaybabum  I'm a little confused about the notion that the URI's have to be unique. I've been stuck on this for over a day.

I have multiple editors on the screen to modify objects that may share a common schema definition.

How can I have two editors display at once with identical URIs?

**Comment by bleathem** [comment]
@steve-heine as I understand it, the unique uri requirement is on the uri of the model, not the uri of the page in the browser.  Think of the model uri as a way of assigning a "filename" to each to the open editors on your page.  I'm using these uris/filenames to assign different schemas to different editors.

**Comment by caffreygo** [comment]
Because I am using multiple monaco editor in one page, and I add extra ts lib for them
and this is useful me:  ( window.monaco.editor.getModels().length === 0 )
![681) BD{C 9Y2E0}XTKG@Z2](https://user-images.githubusercontent.com/38683425/93862452-aa716780-fcf4-11ea-9721-25f4607dcdf3.png)
