### ISSUE TITLE
window.require.config is not a function

### ISSUE THREAD

**Issue by sekar-worx** [atularen/ngx-monaco-editor#5]
If use this plugin in electron it showing error like this 

> ERROR Error: Uncaught (in promise): TypeError: window.require.config is not a function
> TypeError: window.require.config is not a function

**Comment by atul-wizni** [comment]
Its has not been made to be used with electron. You can check some other packages or we have to update it to support electron that can be done in future releases.

**Comment by atul-wizni** [comment]
There are no plan to support electron for now.

**Comment by lozthiensu** [comment]
Fuck plugin, it errror ERROR Error: Uncaught (in promise): TypeError: window.require.config is not a function
