### ISSUE TITLE
Update to latest monaco

### ISSUE THREAD

**Issue by Louis-7** [atularen/ngx-monaco-editor#51]
The monaco you use in your component have a [defect](https://github.com/Microsoft/monaco-editor/issues/839) which block me to to use.  Could you upgrade monaco which use in your component? Or how can I update it by myself?

**Comment by Louis-7** [comment]
Raise a PR to upgrade monaco editor #52

**Comment by atul-wizni** [comment]
monaco has been updated to v0.13.1
