### ISSUE TITLE
Language change not reflecting in editor

### ISSUE THREAD

**Issue by rajatkhare619** [atularen/ngx-monaco-editor#54]
I added the editor on the HTML like this: 

`<ngx-monaco-editor [options]="editorOptions"></ngx-monaco-editor>`

Initially, the options are set to the following object in the component:

` editorOptions = {theme: 'vs-dark', language: 'javascript'};`

I am trying to update the editor's language by changing the 'language' property in the options like this:
I created a button and set up a click event handler on it:

`<button (click)="setHTML()>Set language to HTML</button>`

```
setHTML() {
this.editorOptions.language = 'html';
  }
```

I thought this would change the language in the editor as the options should be bound two way but when I type HTML in the editor, there is no intellisense.

What am I doing wrong?
Is there another way to achieve this?

**Comment by rajatkhare619** [comment]
Never mind.
Got the answer [here](https://github.com/atularen/ngx-monaco-editor/blob/master/src/app/app.component.ts) (Line 73)

**Comment by atul-wizni** [comment]
Editor is re-initialized when options are updated. As angular `@Input` setter detects only object updates only. So property updates are not handled.
