### ISSUE TITLE
Angular 6 app: 'ngx-monaco-editor' is not a known element

### ISSUE THREAD

**Issue by nevadascout** [atularen/ngx-monaco-editor#67]
I am trying to use ngx-monaco-editor in an **Angular 6** application.

Following the exact steps of the readme:

1. Do npm install
2. Add assets to angular-cli.json
3. Add `MonacoEditorModule.forRoot()` to the imports of app.module.ts
4. Try to use in HTML

It gives me this error:

```ERROR in : 'ngx-monaco-editor' is not a known element:
1. If 'ngx-monaco-editor' is an Angular component, then verify that it is part of this module.
2. If 'ngx-monaco-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      <h1>Home</h1>

      [ERROR ->]<ngx-monaco-editor></ngx-monaco-editor>
    </div>
  </div>
")
```

I don't understand what I'm doing wrong; please can someone point me in the right direction?

**Comment by nevadascout** [comment]
Thanks for the suggestion, the assets part of my angular.json file already looks like this:

```
"assets": [
    "src/assets",
    {
        "glob": "**/*",
        "input": "./node_modules/ngx-monaco-editor/assets/monaco",
        "output": "/assets/monaco/"
    }
]
```

**Comment by pareshgami** [comment]
If still you getting error please create demo at https://stackblitz.com/

**Comment by nevadascout** [comment]
I have reproduced the exact problem by creating a new Angular 6 application and following the README steps. Here is the stackblitz:

https://stackblitz.com/edit/angular-yg7vdy

```
'ngx-monaco-editor' is not a known element:
1. If 'ngx-monaco-editor' is an Angular component, then verify that it is part of this module.
2. If 'ngx-monaco-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

**Comment by pareshgami** [comment]
Hi
Don't know something wrong with stackblitz project.

Download this zip and installing node modules and try to run. Hope that will run for you

https://drive.google.com/file/d/1W_1j2JmGyvaE_a9nAXONrsqN8DIsH9pk/view?usp=sharing

**Comment by nevadascout** [comment]
It now works, I had to add the `MonacoEditorModule.forRoot()` import into the module that I was using monaco in.

Seems like you need to do this if you have a multi-module app (as I do)!

**Comment by lucas-cota** [comment]
fiz todos os procedimentos acima, mas obtenho o mesmo erro
