### ISSUE TITLE
Access global monaco object before editor creation.

### ISSUE THREAD

**Issue by Jelledb** [atularen/ngx-monaco-editor#7]
I want to use this piece of code:
```
monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
	noSemanticValidation: true,
	noSyntaxValidation: false
});
```

However, when the Angular component is initializing, the monaco object is undefined, and my component crashes. The only way I could access it is using the onInit() event, but then the editor is already initialized so the code mentioned above doesn't work anymore.

Is it possible to achieve what I want?

**Comment by viccsjain** [comment]
@Jelledb 
How do you get monaco object in onInit method ?

**Comment by atul-wizni** [comment]
@viccsjain check sample [here](https://github.com/atularen/ngx-monaco-editor#custom-operations)

**Comment by viccsjain** [comment]
Thanks for replying @atul-wizni .
OnInit method will give editor object.
But my question is How to get monaco object ?

**Comment by bluelightning2k** [comment]
@atul-wizni firstly - thank you for this component, it's very appreciated

@viccsjain I had the same exact issue. The key for me was realising that the monaco object is globally available. So in my onInit code I have let monaco = window['monaco'] and then it all works.

**Comment by atul-wizni** [comment]
@bluelightning2k is right monaco object will be available globally after onInit.

But there is no support for accessing monaco object before editor initialization. I will find out some way to handle that.

**Comment by nghiangodinh** [comment]
Hello @atul-wizni , do you find the solution for below issue?  If I need to define new language, I have to access monaco object before editor initialization happening.
Thanks,

> But there is no support for accessing monaco object before editor initialization. I will find out some way to handle that.

**Comment by atul-wizni** [comment]
v2.0.0 supports to pass a function to be executed after monaco loaded and before editor initialization. for more details refer [README -> Configurations](https://github.com/atularen/ngx-monaco-editor#configurations)

**Comment by nghiangodinh** [comment]
Thanks @atul-wizni. Great! It is really help! ;)
