### ISSUE TITLE
::host height 200px

### ISSUE THREAD

**Issue by johnnliu** [atularen/ngx-monaco-editor#75]
Implementing ngx-monaco-editor within a dialog component, I was confused why the control sticks to a 200px height.
I noticed a ::host style in the editor component.

is that necessary?

**Comment by johnnliu** [comment]
https://github.com/atularen/ngx-monaco-editor/blob/master/src/platform/editor/editor.component.ts#L16

**Comment by johnnliu** [comment]
I missed the style comment on the front page - so I can override it now.  the rule I set wasn't specific enough previously.

**Comment by hakimovic** [comment]
Hello @johnnliu,
how did you manage increasing the height of the editor?
I tried to add this config 
```
  editorOptions = {
    automaticLayout: true,
    theme: 'vs-dark',
    language: 'html',
  };
```
and scss
```
.template-editor {
  .editorContainer {
    height: 800px;
  }
}
```
but it's still at 98% in my material dialog...
Thanks for your answers!

**Comment by SteveStrong** [comment]
I am having the same problems

**Comment by hakimovic** [comment]
finally I succeeded by writting the style directly in the `.template-editor` instead of `.editorContainer`
scss
```
.template-editor {
    height: 800px;
}
```
html
```
<ngx-monaco-editor class="template-editor" [options]="editorOptions" [(ngModel)]="code">
</ngx-monaco-editor>
```

**Comment by SteveStrong** [comment]
thank you ,  I will try this also.
