### ISSUE TITLE
File Change Event

### ISSUE THREAD

**Issue by johnsdav** [atularen/ngx-monaco-editor#77]
Hello,

I'm hoping to listen file change events in the editor to trigger other parts of my application. For example, validating their file against a remote server. I would like to suggest additional events besides onInit such as fileChange and onDestroy or onClose.

**Comment by indianazhao** [comment]
Try this: `(ngModelChange)="onChange($event)"`

**Comment by zsydyc** [comment]
@indianazhao your solution works for me.
But what should I do if I want a short delay to this onChange event?

**Comment by AbuDawood** [comment]
```
// here is a sample
 class __ {

   onChangeTimestamp;

  onChange(arg) {

    console.log('updating ... ')
    if( onChangeTimestamp)
         clearTimeout(this.onChangeTimestamp);

      this.onChangeTimestamp = setTimeout(()=>{
          /*do your action*/
          console.log('I am done after a delay')
     }, 1000 /*set the delay*/)

}


}
```

**Comment by AbuDawood** [comment]
> @indianazhao your solution works for me.
> But what should I do if I want a short delay to this onChange event?
```
// here is a sample
 class __ {

   onChangeTimestamp;

  onChange(arg) {

    console.log('updating ... ')
    if( onChangeTimestamp)
         clearTimeout(this.onChangeTimestamp);

      this.onChangeTimestamp = setTimeout(()=>{
          /*do your action*/
          console.log('I am done after a delay')
     }, 1000 /*set the delay*/)

}


}
```
