### ISSUE TITLE
This is not working in IE11

### ISSUE THREAD

**Issue by madhu23rima** [atularen/ngx-monaco-editor#78]
It does not seem to be working in IE11. Works fine in Chrome and Edge.

**Comment by madhu23rima** [comment]
This is working after updating the polyfills
import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es7/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/weak-map';
 import 'core-js/es6/set';
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';

**Comment by namnn96** [comment]
I am with Angular 8, I can edit in Chrome but not in IE.
Already added the above polyfills but didn't work.
Can you please assist?

**Comment by musso** [comment]
It's due to the Proxy object [fix](https://github.com/GoogleChrome/proxy-polyfill)
