### ISSUE TITLE
Allow Custom Auto Complete

### ISSUE THREAD

**Issue by hafridign** [atularen/ngx-monaco-editor#8]
Is there a way to do auto complete with custom snippets?

**Comment by atul-wizni** [comment]
it can be done by registering completion items with 
monaco.languages.registerCompletionItemProvider 

but that possible only when you have access to monaco object before editor initialization. #7

**Comment by buchmiller** [comment]
I was able to get custom autocomplete with the following code:
```html
<!-- monaco.component.html -->
<ngx-monaco-editor [options]="editorOptions" [(ngModel)]="code" (onInit)="onInit($event)" #editor></ngx-monaco-editor>
```

```typescript
// monaco.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-monaco',
  templateUrl: './monaco.component.html',
  styleUrls: ['./monaco.component.css']
})
export class MonacoComponent {
  editorOptions = { theme: 'vs-dark', language: 'sql' };
  code = 'SELECT * FROM Table_1';

  onInit(editor) {
    const monaco = window['monaco'];
    monaco.languages.registerCompletionItemProvider('sql', this.getSqlCompletionProvider(monaco));
  }

  getSqlCompletionProvider(monaco) {
    return {
      provideCompletionItems: function (model, position) {
        const completionItems = [
          {
            label: 'SELECT',
            kind: monaco.languages.CompletionItemKind.Keyword,
            detail: 'SQL',
            documentation: 'sql selector.'
          }
        ];
        return completionItems;
      }
    };
  }
}

```

**Comment by baggiaraj** [comment]
> ```ts
> 
> export class MonacoComponent {
>   editorOptions = { theme: 'vs-dark', language: 'sql' };
>   code = 'SELECT * FROM Table_1';
> 
>   onInit(editor) {
>     const monaco = window['monaco'];
>     monaco.languages.registerCompletionItemProvider('sql', this.getSqlCompletionProvider(monaco));
>   }
> 
>   getSqlCompletionProvider(monaco) {
>     return {
>       provideCompletionItems: function (model, position) {
>         const completionItems = [
>           {
>             label: 'SELECT',
>             kind: monaco.languages.CompletionItemKind.Keyword,
>             detail: 'SQL',
> ```

can you please provice  executable code stackblitz or fiddle

**Comment by gucci-quoci** [comment]
So I managed to make auto completion work. But now I don't get any auto completion for variables declaration, while loops, etc. It worked fine before I registered new completion items. How can I fix that?
Here my code https://stackblitz.com/edit/angular-7-master-5eyyep

**Comment by mike-luabase** [comment]
I had to change @buchmiller a bit. Also note the `insertText` key in the completionItem

```
getSqlCompletionProvider(monaco) {
      return {
        provideCompletionItems: function (model, position) {
          const container = {}
          const completionItems = [
            {
              label: 'SELECT',
              insertText: 'SELECT',
              kind: monaco.languages.CompletionItemKind.Keyword,
              detail: 'SQL',
              documentation: 'sql selector.'
            }
          ];
          container.suggestions = completionItems
          return container;
        }
      };
    },
```

full code in part of a vuejs app

```
let editor = monaco.editor.create(document.getElementById('monaco'), {
      value: this.sql,
      language: 'sql',
      theme: 'luabaseDark',
      minimap: {
        enabled: false
      },
      padding: {
        top: 10,
        bottom: 10,
        left: 10,
        right: 10
      },
      overviewRulerLanes: 0,
        hideCursorInOverviewRuler: true,
        scrollbar: {
            vertical: 'hidden'
        },
        overviewRulerBorder: false,
    });
    editor.onDidChangeModelContent(() => {
      this.sql = editor.getValue();
    });
    monaco.languages.registerCompletionItemProvider('sql', this.getSqlCompletionProvider(monaco));
```
