### ISSUE TITLE
Support for Reactive Forms

### ISSUE THREAD

**Issue by skylarmb** [atularen/ngx-monaco-editor#82]
Would be nice to support reactive / model driven forms as this seems to be the preferred method for input / forms in angular going forward.

https://angular.io/guide/reactive-forms

**Comment by markhus-aurelius** [comment]
Already supported. Add the reactive directives and you're good to go.

**Comment by fwitkowski** [comment]
Can you give example how to make it work?
When I am adding form:
formControlName="inputName"
it just does not work - blank (black) rectangle.
